import {
  Event,
  BudgetItem,
  Artist,
  Vendor,
  VendorQuotation,
  PurchaseOrder,
  RevenueItem,
  Client,
  Venue,
  CrewAssignment,
  Task,
  Milestone,
  RundownItem,
  RiskItem,
  ApprovalRequest,
  PaymentRecord,
  DocumentItem,
  AuditLogItem,
  UserAccount,
  EventTemplate,
  EventRequirement,
  NotificationItem,
} from '@/lib/types';

export const SEED_USERS: UserAccount[] = [
  {
    id: 'usr-001',
    name: 'Bima Satria Wardhana',
    email: 'bima.wardhana@eventpro.co.id',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    department: 'Executive Management',
    permissions: ['all'],
  },
  {
    id: 'usr-002',
    name: 'Citra Kirana Dewi',
    email: 'citra.dewi@eventpro.co.id',
    role: 'EVENT_DIRECTOR',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    department: 'Event Direction',
    permissions: ['events:read', 'events:write', 'budget:read', 'approvals:manage', 'reports:read'],
  },
  {
    id: 'usr-003',
    name: 'Dimas Arioseno',
    email: 'dimas.ario@eventpro.co.id',
    role: 'PROJECT_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    department: 'Operations',
    permissions: ['events:read', 'events:write', 'tasks:manage', 'timeline:manage', 'rundown:manage'],
  },
  {
    id: 'usr-004',
    name: 'Ratna Ayu Larasati',
    email: 'ratna.larasati@eventpro.co.id',
    role: 'FINANCE',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    department: 'Finance & Treasury',
    permissions: ['budget:manage', 'payments:manage', 'revenue:manage', 'approvals:manage', 'reports:read'],
  },
  {
    id: 'usr-005',
    name: 'Hendra Setiawan',
    email: 'hendra.setiawan@eventpro.co.id',
    role: 'TECHNICAL_MANAGER',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    department: 'Technical & Production',
    permissions: ['vendors:manage', 'procurement:manage', 'logistics:manage', 'rundown:manage'],
  },
  {
    id: 'usr-006',
    name: 'Nadia Putri',
    email: 'nadia.putri@eventpro.co.id',
    role: 'PROCUREMENT',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    department: 'Procurement',
    permissions: ['vendors:manage', 'procurement:manage', 'po:manage'],
  },
];

export const SEED_CLIENTS: Client[] = [
  {
    id: 'cli-001',
    company: 'Badan Eksekutif Mahasiswa KM UGM',
    contactPerson: 'Aditya Pratama (Ketua Panitia)',
    email: 'bem.km@ugm.ac.id',
    phone: '+62 812-3456-7890',
    address: 'Gelanggang Mahasiswa UGM, Bulaksumur, Sleman, DI Yogyakarta',
    industry: 'Education & Student Affairs',
    taxInformation: 'NPWP: 00.123.456.7-542.000',
    notes: 'Klien tahunan untuk konser akbar Dies Natalis. Pembayaran termin terstruktur.',
    totalEvents: 1,
    activeEvents: 1,
    completedEvents: 0,
    totalRevenue: 3750000000,
    outstandingReceivable: 450000000,
  },
  {
    id: 'cli-002',
    company: 'PT Nada Nusantara Kreasi',
    contactPerson: 'Siti Rahmawati',
    email: 'siti@nadanusantara.id',
    phone: '+62 811-9876-5432',
    address: 'Menara Palma Lt. 18, Jl. HR Rasuna Said, Jakarta Selatan',
    industry: 'Entertainment & Music Promoter',
    taxInformation: 'NPWP: 01.998.887.6-012.000',
    notes: 'Promotor musik nasional terkemuka.',
    totalEvents: 4,
    activeEvents: 1,
    completedEvents: 3,
    totalRevenue: 9800000000,
    outstandingReceivable: 850000000,
  },
  {
    id: 'cli-003',
    company: 'Nexa Enterprise Technologies Pte Ltd',
    contactPerson: 'Marcus Wong',
    email: 'marcus.wong@nexa-tech.com',
    phone: '+62 813-5555-1234',
    address: 'Pacific Century Place Lt. 24, SCBD Sudirman, Jakarta Selatan',
    industry: 'Enterprise Software & Cloud AI',
    taxInformation: 'NPWP: 31.456.789.0-062.000',
    notes: 'Regional tech leader hosting annual APAC summit.',
    totalEvents: 2,
    activeEvents: 1,
    completedEvents: 1,
    totalRevenue: 4200000000,
    outstandingReceivable: 0,
  },
  {
    id: 'cli-004',
    company: 'PT Aura Kosmetika Mandiri',
    contactPerson: 'Elena Wijaya',
    email: 'elena@aurabeauty.co.id',
    phone: '+62 812-7777-8899',
    address: 'The Energy Building Lt. 12, SCBD, Jakarta',
    industry: 'Beauty & Lifestyle Brand',
    taxInformation: 'NPWP: 02.345.678.9-011.000',
    notes: 'Brand activation and new product launch series.',
    totalEvents: 2,
    activeEvents: 1,
    completedEvents: 1,
    totalRevenue: 1650000000,
    outstandingReceivable: 250000000,
  },
  {
    id: 'cli-005',
    company: 'Kementerian Pariwisata dan Ekonomi Kreatif RI',
    contactPerson: 'Drs. Iwan Setiawan, M.M.',
    email: 'kerjasama.event@kemenparekraf.go.id',
    phone: '+62 811-2233-4455',
    address: 'Gedung Sapta Pesona, Jl. Medan Merdeka Barat No. 17, Jakarta Pusat',
    industry: 'Government & Public Sector',
    taxInformation: 'NPWP: 00.001.234.5-071.000',
    notes: 'Program resmi promosi kebudayaan dan pariwisata nasional.',
    totalEvents: 5,
    activeEvents: 1,
    completedEvents: 4,
    totalRevenue: 6400000000,
    outstandingReceivable: 600000000,
  },
];

export const SEED_VENUES: Venue[] = [
  {
    id: 'ven-001',
    name: 'Stadion Mandala Krida',
    address: 'Jl. Kemuning No. 1, Semaki, Umbulharjo',
    city: 'Yogyakarta',
    capacity: 25000,
    type: 'Outdoor',
    contactPerson: 'Bambang Kusuma',
    contactPhone: '+62 812-2345-6789',
    rentalCost: 185000000,
    parkingCapacity: '3.500 motor, 800 mobil, 50 bus',
    loadingAreaSpecs: 'Gate Barat 6m x 5m direct access, aspal datar untuk trailer 40ft',
    powerCapacity: 'PLN 197 kVA + Genset 3x 250 kVA Synchronized',
    restrictions: 'Batas sound level 105 dB di FOH, curfew ketat pukul 23:00 WIB',
    curfewTime: '23:00 WIB',
    notes: 'Venue legendaris di pusat kota Yogyakarta, drainase lapangan baik.',
  },
  {
    id: 'ven-002',
    name: 'Indonesia Arena GBK',
    address: 'Kawasan Gelora Bung Karno, Senayan',
    city: 'Jakarta Pusat',
    capacity: 16500,
    type: 'Indoor',
    contactPerson: 'Reza Fahlevi',
    contactPhone: '+62 813-9876-1234',
    rentalCost: 450000000,
    parkingCapacity: 'Area parkir terpadu GBK 10.000 kendaraan',
    loadingAreaSpecs: 'Tunnel loading bay ground floor, rigging point certified 25 ton',
    powerCapacity: 'PLN 1.200 kVA Dedicated Substation + UPS 250 kVA',
    restrictions: 'Dilarang menggunakan bahan peledak/pyro tanpa izin khusus Gegana Polri',
    curfewTime: '24:00 WIB',
    notes: 'Indoor arena tercanggih berstandar FIBA, akustik berpanel absorber.',
  },
  {
    id: 'ven-003',
    name: 'Indonesia Convention Exhibition (ICE) BSD - Hall 1 & 2',
    address: 'Jl. BSD Grand Boulevard No. 1, Pagedangan',
    city: 'Tangerang',
    capacity: 10000,
    type: 'Indoor',
    contactPerson: 'Stephanie Halim',
    contactPhone: '+62 812-8888-9900',
    rentalCost: 320000000,
    parkingCapacity: 'Gedung parkir 5.000 mobil',
    loadingAreaSpecs: 'Loading dock loading height 1.2m, 6 container bays simultan',
    powerCapacity: 'PLN 800 kVA + 100% Redundant Genset',
    restrictions: 'Floor loading capacity 2.000 kg/m2, ceiling hanging max 1.500 kg per node',
    curfewTime: '23:30 WIB',
    notes: 'Ideal untuk konferensi teknologi multinasional & expo.',
  },
  {
    id: 'ven-004',
    name: 'Senayan Park (SPARK) Floating Island & Atrium',
    address: 'Jl. Gerbang Pemuda No. 3, Gelora, Tanah Abang',
    city: 'Jakarta Pusat',
    capacity: 3500,
    type: 'Hybrid',
    contactPerson: 'David Kurniawan',
    contactPhone: '+62 811-1234-9988',
    rentalCost: 140000000,
    parkingCapacity: '1.200 mobil',
    loadingAreaSpecs: 'Loading ramp basement ke main atrium via service freight elevator 3 ton',
    powerCapacity: 'PLN 350 kVA',
    restrictions: 'Dekorasi panggung tidak boleh menutup jalur darurat mal',
    curfewTime: '22:00 WIB',
    notes: 'Lokasi populer untuk brand activation anak muda dan konser intimate.',
  },
  {
    id: 'ven-005',
    name: 'Gedung Kesenian Jakarta',
    address: 'Jl. Gedung Kesenian No. 1, Pasar Baru, Sawah Besar',
    city: 'Jakarta Pusat',
    capacity: 500,
    type: 'Indoor',
    contactPerson: 'Hj. Endang Suryani',
    contactPhone: '+62 812-4455-6677',
    rentalCost: 75000000,
    parkingCapacity: '200 kendaraan VIP',
    loadingAreaSpecs: 'Pintu panggung samping, manual unloading trolley',
    powerCapacity: 'PLN 150 kVA',
    restrictions: 'Bangunan cagar budaya heritage, dilarang melubangi dinding atau lantai',
    curfewTime: '22:30 WIB',
    notes: 'Teater proscenium klasik dengan akustik alami terbaik di Indonesia.',
  },
];

export const SEED_VENDORS: Vendor[] = [
  {
    id: 'vnd-001',
    name: 'PT Sumber Audio Visual Mandiri',
    company: 'SAV Mandiri Acoustics',
    category: 'Sound',
    contactPerson: 'Ir. Johanes Handoko',
    phone: '+62 811-3344-5566',
    email: 'johanes@sav-audio.co.id',
    address: 'Kawasan Industri Pulogadung Blok F-4, Jakarta Timur',
    npwp: '01.234.567.8-005.000',
    bankName: 'Bank Central Asia (BCA)',
    bankAccountNumber: '542-019-8821',
    bankAccountHolder: 'PT Sumber Audio Visual Mandiri',
    rating: 5,
    notes: 'Penyedia official L-Acoustics K-Series & Digico Consoles di Indonesia.',
    activeEventsCount: 3,
  },
  {
    id: 'vnd-002',
    name: 'Mata Elang Production',
    company: 'PT Mata Elang International',
    category: 'Stage',
    contactPerson: 'Gunawan Prasetyo',
    phone: '+62 812-8899-0011',
    email: 'gunawan@mataelang.com',
    address: 'Jl. Daan Mogot KM 11 No. 45, Jakarta Barat',
    npwp: '02.456.789.1-034.000',
    bankName: 'Bank Mandiri',
    bankAccountNumber: '118-00-1234567-9',
    bankAccountHolder: 'PT Mata Elang International',
    rating: 5,
    notes: 'Spesialis mega-stage scaffolding, Layher system, aluminium rigging & roofing truss.',
    activeEventsCount: 4,
  },
  {
    id: 'vnd-003',
    name: 'Citra Visual Mandiri (CVM)',
    company: 'PT Citra Visual Mandiri',
    category: 'LED',
    contactPerson: 'Rudi Hartono',
    phone: '+62 813-1122-3344',
    email: 'rudi@cvm-led.com',
    address: 'Jl. Panjang No. 88, Kebon Jeruk, Jakarta Barat',
    npwp: '03.789.123.4-085.000',
    bankName: 'BCA',
    bankAccountNumber: '288-901-2234',
    bankAccountHolder: 'PT Citra Visual Mandiri',
    rating: 5,
    notes: 'Indoor & Outdoor LED P3.9 & P2.6 curve panels, Brompton processor, Novastar 4K.',
    activeEventsCount: 2,
  },
  {
    id: 'vnd-004',
    name: 'PowerMax Genset & Energy Solution',
    company: 'PT Daya Solusi Nusantara',
    category: 'Generator',
    contactPerson: 'Agus Triyono',
    phone: '+62 812-4455-7788',
    email: 'agus@powermax.id',
    address: 'Jl. Magelang KM 7, Mlati, Sleman, Yogyakarta',
    npwp: '04.567.890.1-541.000',
    bankName: 'Bank BNI',
    bankAccountNumber: '021-9988-771',
    bankAccountHolder: 'PT Daya Solusi Nusantara',
    rating: 4,
    notes: 'Silent Diesel Generator 250 kVA - 500 kVA Cummins & Perkins engine.',
    activeEventsCount: 2,
  },
  {
    id: 'vnd-005',
    name: 'Rasa Nusantara Catering & Hospitality',
    company: 'CV Rasa Nusantara Boga',
    category: 'Catering',
    contactPerson: 'Ibu Ratmi Sudarsono',
    phone: '+62 811-7788-9900',
    email: 'info@rasanusantara.id',
    address: 'Jl. Colombo No. 14, Sleman, Yogyakarta',
    npwp: '05.678.901.2-542.000',
    bankName: 'BCA',
    bankAccountNumber: '037-123-4567',
    bankAccountHolder: 'CV Rasa Nusantara Boga',
    rating: 5,
    notes: 'Penyedia catering artist rider, VIP buffet, dan 350 box meal crew harian.',
    activeEventsCount: 1,
  },
  {
    id: 'vnd-006',
    name: 'Garda Wibawa Security & Crowd Control',
    company: 'PT Garda Wibawa Solusi',
    category: 'Security',
    contactPerson: 'Kapten (Purn) Suryanto',
    phone: '+62 812-9900-1122',
    email: 'ops@gardawibawa.co.id',
    address: 'Jl. Solo KM 9 No. 20, Kalasan, Sleman',
    npwp: '06.789.012.3-541.000',
    bankName: 'Bank Mandiri',
    bankAccountNumber: '137-00-8877665-2',
    bankAccountHolder: 'PT Garda Wibawa Solusi',
    rating: 5,
    notes: '150 personil bersertifikat Gada Pratama, briefing koordinasi dengan Polresta & Polda.',
    activeEventsCount: 3,
  },
  {
    id: 'vnd-007',
    name: 'Flash Production Lighting & Special Effects',
    company: 'PT Cahaya Kilau Abadi',
    category: 'Lighting',
    contactPerson: 'Donny Wicaksono',
    phone: '+62 813-4455-6677',
    email: 'donny@flashlighting.co.id',
    address: 'Komplek Pergudangan Infinia Park Kav B-7, Tebet, Jakarta Selatan',
    npwp: '07.890.123.4-015.000',
    bankName: 'BCA',
    bankAccountNumber: '680-019-3341',
    bankAccountHolder: 'PT Cahaya Kilau Abadi',
    rating: 5,
    notes: 'Robe MegaPointe, ClayPaky Sharpy Plus, Martin MAC Aura, GrandMA3 Full Size.',
    activeEventsCount: 3,
  },
];

export const SEED_TEMPLATES: EventTemplate[] = [
  {
    id: 'tpl-001',
    name: 'Music Festival & Outdoor Concert Template',
    eventType: 'Music Festival',
    description: 'Struktur baku multi-stage festival musik: talent riders, L-Acoustics audio, crowd control, perizinan kepolisian.',
    estimatedDurationDays: 3,
    defaultChecklist: [
      'Venue Confirmation & Contract',
      'Artis Headliner Contract & Riders Signed',
      'Perizinan Kepolisian (Mabes Polri / Polda / Polres)',
      'Vendor Sound & Lighting PO Issued',
      'Genset & Power Distribution Plan',
      'Ambulance & Medical Team Standby',
      'Asuransi Public Liability Event',
      'Technical Meeting dengan Manajemen Artis',
      'Rundown & Show Cue Approval',
      'Load In & Soundcheck Schedule',
    ],
    defaultMilestones: [
      'Proposal & Artist Booking',
      'Venue & Permit Submission',
      'Vendor Procurement & PO',
      'Production Meeting',
      'Load In & Rigging Setup',
      'Technical & Sound Check',
      'Festival Day 1',
      'Festival Day 2',
      'Festival Day 3',
      'Strike & Load Out',
      'Financial Settlement',
    ],
    defaultCategories: [
      'ARTIST_TALENT',
      'VENUE',
      'PRODUCTION',
      'CREATIVE',
      'MARKETING',
      'OPERATIONS',
      'ADMINISTRATION',
      'CONTINGENCY',
    ],
    defaultRoles: [
      'Event Director',
      'Project Manager',
      'Production Manager',
      'Stage Manager',
      'Show Caller',
      'FOH Audio Engineer',
      'Lighting Director',
      'Security Coordinator',
      'Liaison Officer (LO)',
    ],
  },
  {
    id: 'tpl-002',
    name: 'Corporate Conference & Tech Summit Template',
    eventType: 'Corporate Event',
    description: 'Template untuk konferensi korporat internasional, breakout rooms, keynote speakers, dan hybrid live-streaming.',
    estimatedDurationDays: 2,
    defaultChecklist: [
      'Keynote Speaker Confirmation',
      'Hotel & Flight Booking for VIPs',
      'Audio Visual & LED P2.6 Screens',
      'Simultaneous Translation Equipment',
      'Catering Buffet & Coffee Breaks',
      'Registration & Badge Printing System',
      'Dry Run & Speaker Rehearsal',
    ],
    defaultMilestones: [
      'Speaker Lineup Confirmed',
      'Sponsor Package Finalized',
      'Venue & AV Setup',
      'Speaker Rehearsal',
      'Conference Day 1',
      'Conference Day 2',
      'Post Conference Survey & Settlement',
    ],
    defaultCategories: [
      'ARTIST_TALENT',
      'VENUE',
      'PRODUCTION',
      'CREATIVE',
      'MARKETING',
      'OPERATIONS',
      'ADMINISTRATION',
    ],
    defaultRoles: [
      'Event Director',
      'Project Manager',
      'Show Caller',
      'Video & Stream Engineer',
      'Speaker Concierge',
    ],
  },
];

// 5 DETAILED REALISTIC EVENTS
export const SEED_EVENTS: Event[] = [
  {
    id: 'evt-001',
    code: 'EVT-2027-UGM',
    name: 'Gadjah Mada Youth Music & Arts Festival 2027',
    type: 'University Festival',
    clientId: 'cli-001',
    clientName: 'Badan Eksekutif Mahasiswa KM UGM',
    clientContact: 'Aditya Pratama (+62 812-3456-7890)',
    description:
      'Festival musik dan seni mahasiswa terbesar di Indonesia menghadirkan Sheila On 7, Hindia, Reality Club, dan Dipha Barus dengan target 22.000 penonton di Stadion Mandala Krida Yogyakarta.',
    objective:
      'Memperingati Dies Natalis UGM ke-77 dengan pementasan budaya nusantara, pertunjukan musik megah berstandar internasional, serta pemberdayaan UMKM kuliner kreatif.',
    theme: 'Harmoni Nusantara: Suara Generasi Masa Depan',
    venueId: 'ven-001',
    venueName: 'Stadion Mandala Krida',
    venueAddress: 'Jl. Kemuning No. 1, Semaki, Umbulharjo',
    city: 'Yogyakarta',
    province: 'DI Yogyakarta',
    country: 'Indonesia',
    startDate: '2027-05-14T08:00:00Z',
    endDate: '2027-05-16T23:30:00Z',
    loadInDate: '2027-05-11T08:00:00Z',
    setupDate: '2027-05-12T08:00:00Z',
    technicalRehearsalDate: '2027-05-13T14:00:00Z',
    generalRehearsalDate: '2027-05-13T19:00:00Z',
    eventDayDate: '2027-05-15T15:00:00Z',
    strikeDate: '2027-05-17T00:00:00Z',
    loadOutDate: '2027-05-17T20:00:00Z',
    expectedAttendance: 22000,
    actualAttendance: 23450,
    status: 'PRODUCTION',
    priority: 'CRITICAL',
    pics: {
      projectManager: 'Dimas Arioseno',
      eventPIC: 'Citra Kirana Dewi',
      financePIC: 'Ratna Ayu Larasati',
      productionPIC: 'Hendra Setiawan',
      technicalPIC: 'Ir. Johanes Handoko',
      creativePIC: 'Nadia Putri',
      salesPIC: 'Aditya Pratama',
    },
    totalBudget: 2850000000,
    estimatedCost: 2850000000,
    actualCost: 2795000000,
    committedCost: 2820000000,
    totalRevenue: 3750000000,
    actualRevenue: 3820000000,
    receivedRevenue: 3370000000,
    currency: 'IDR',
    createdAt: '2026-11-10T10:00:00Z',
    updatedAt: '2027-05-02T14:30:00Z',
    tags: ['Mega Festival', 'Live Music', 'Youth', 'Outdoor Stadium', 'Sheila On 7'],
  },
];

// COMPREHENSIVE BUDGET ITEMS FOR EVENT 001 (UGM Festival) + other events
export const SEED_BUDGET_ITEMS: BudgetItem[] = [
  // Event 001: Artist & Talent
  {
    id: 'bdg-001',
    eventId: 'evt-001',
    category: 'ARTIST_TALENT',
    categoryLabel: 'Artist & Talent',
    subcategory: 'Headliner Fee',
    description: 'Sheila On 7 - Full Performance Set (90 min) & Production Rider',
    vendorId: 'vnd-001',
    vendorName: '507 Management',
    quantity: 1,
    unit: 'show',
    estimatedUnitCost: 450000000,
    estimatedTotal: 450000000,
    actualUnitCost: 450000000,
    actualTotal: 450000000,
    variance: 0,
    taxRate: 2.5, // PPh 21
    taxAmount: 11250000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PARTIALLY_PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-10',
    notes: 'DP 50% telah dibayarkan saat tanda tangan kontrak. Pelunasan H-5 show.',
    paidAmount: 225000000,
  },
  {
    id: 'bdg-002',
    eventId: 'evt-001',
    category: 'ARTIST_TALENT',
    categoryLabel: 'Artist & Talent',
    subcategory: 'Supporting Artist Fee',
    description: 'Hindia - Band Live Set (60 min)',
    vendorName: 'Sun Eater Management',
    quantity: 1,
    unit: 'show',
    estimatedUnitCost: 125000000,
    estimatedTotal: 125000000,
    actualUnitCost: 125000000,
    actualTotal: 125000000,
    variance: 0,
    taxRate: 2.5,
    taxAmount: 3125000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-01',
    notes: 'Lunas 100%. Hotel di Tentrem Yogyakarta.',
    paidAmount: 125000000,
  },
  {
    id: 'bdg-003',
    eventId: 'evt-001',
    category: 'ARTIST_TALENT',
    categoryLabel: 'Artist & Talent',
    subcategory: 'Supporting Artist Fee',
    description: 'Reality Club - Indie Pop Band Live Set (50 min)',
    vendorName: 'Dominion Records',
    quantity: 1,
    unit: 'show',
    estimatedUnitCost: 85000000,
    estimatedTotal: 85000000,
    actualUnitCost: 85000000,
    actualTotal: 85000000,
    variance: 0,
    taxRate: 2.5,
    taxAmount: 2125000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PARTIALLY_PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-08',
    notes: 'DP 50% terbayar.',
    paidAmount: 42500000,
  },
  {
    id: 'bdg-004',
    eventId: 'evt-001',
    category: 'ARTIST_TALENT',
    categoryLabel: 'Artist & Talent',
    subcategory: 'DJ Set Fee',
    description: 'Dipha Barus ft. Vocalist - Midnight Electronic Dance Set (60 min)',
    vendorName: 'Pon Your Tone',
    quantity: 1,
    unit: 'show',
    estimatedUnitCost: 75000000,
    estimatedTotal: 75000000,
    actualUnitCost: 75000000,
    actualTotal: 75000000,
    variance: 0,
    taxRate: 2.5,
    taxAmount: 1875000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'SCHEDULED',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-12',
    notes: 'Jatuh tempo pelunasan 12 Mei.',
    paidAmount: 0,
  },
  {
    id: 'bdg-005',
    eventId: 'evt-001',
    category: 'ARTIST_TALENT',
    categoryLabel: 'Artist & Talent',
    subcategory: 'Talent Hospitality & Accommodation',
    description: 'Sewa 18 Kamar Suite & Deluxe Hotel Tentrem (3 malam) + 4 Alphard & HiAce',
    vendorName: 'Tentrem Hotel & Rental',
    quantity: 1,
    unit: 'paket',
    estimatedUnitCost: 110000000,
    estimatedTotal: 110000000,
    actualUnitCost: 118000000,
    actualTotal: 118000000,
    variance: -8000000, // OVER BUDGET WARNING!
    taxRate: 10,
    taxAmount: 11800000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PARTIALLY_PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-10',
    notes: 'Over budget Rp 8.000.000 akibat penambahan 2 kamar ekstra untuk kru sound Sheila On 7.',
    paidAmount: 60000000,
  },

  // Event 001: Venue
  {
    id: 'bdg-006',
    eventId: 'evt-001',
    category: 'VENUE',
    categoryLabel: 'Venue',
    subcategory: 'Venue Rental',
    description: 'Sewa Stadion Mandala Krida (6 hari: Load In s/d Load Out)',
    vendorId: 'ven-001',
    vendorName: 'Balai Pemuda & Olahraga Disdikpora DIY',
    quantity: 6,
    unit: 'hari',
    estimatedUnitCost: 30000000,
    estimatedTotal: 180000000,
    actualUnitCost: 30000000,
    actualTotal: 180000000,
    variance: 0,
    taxRate: 0,
    taxAmount: 0,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-04-15',
    notes: 'Retribusi resmi sewa stadion lunas.',
    paidAmount: 180000000,
  },
  {
    id: 'bdg-007',
    eventId: 'evt-001',
    category: 'VENUE',
    categoryLabel: 'Venue',
    subcategory: 'Venue Cleaning & Waste Management',
    description: 'Tim kebersihan 40 personil selama 3 hari + armada truk DLH Kota Yogyakarta',
    vendorName: 'Eco Clean Solution',
    quantity: 1,
    unit: 'paket',
    estimatedUnitCost: 45000000,
    estimatedTotal: 45000000,
    actualUnitCost: 42000000,
    actualTotal: 42000000,
    variance: 3000000, // SAVINGS
    taxRate: 11,
    taxAmount: 4620000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-16',
    notes: 'Negosiasi berhasil mendapatkan diskon paket pemilahan sampah daur ulang.',
    paidAmount: 42000000,
  },

  // Event 001: Production
  {
    id: 'bdg-008',
    eventId: 'evt-001',
    category: 'PRODUCTION',
    categoryLabel: 'Production',
    subcategory: 'Stage & Rigging',
    description: 'Main Stage Layher 24m x 16m x 14m roofing clearance, wings LED rigging & FOH tower 2-storey',
    vendorId: 'vnd-002',
    vendorName: 'Mata Elang Production',
    quantity: 1,
    unit: 'set',
    estimatedUnitCost: 320000000,
    estimatedTotal: 320000000,
    actualUnitCost: 320000000,
    actualTotal: 320000000,
    variance: 0,
    taxRate: 11,
    taxAmount: 35200000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PARTIALLY_PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-11',
    notes: 'PO-2027-001 diterbitkan. Sertifikat uji beban wind-load 60 km/h terpenuhi.',
    paidAmount: 160000000,
  },
  {
    id: 'bdg-009',
    eventId: 'evt-001',
    category: 'PRODUCTION',
    categoryLabel: 'Production',
    subcategory: 'Sound System FOH',
    description: 'L-Acoustics K2 Line Array (24 boxes), KS28 Sub (16 boxes), Kara II Outfill, Digico SD7 FOH & Monitor',
    vendorId: 'vnd-001',
    vendorName: 'PT Sumber Audio Visual Mandiri',
    quantity: 1,
    unit: 'set',
    estimatedUnitCost: 380000000,
    estimatedTotal: 380000000,
    actualUnitCost: 380000000,
    actualTotal: 380000000,
    variance: 0,
    taxRate: 11,
    taxAmount: 41800000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PARTIALLY_PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-11',
    notes: 'Termasuk sertifikasi sistem engineer L-Acoustics K-Standard.',
    paidAmount: 190000000,
  },
  {
    id: 'bdg-010',
    eventId: 'evt-001',
    category: 'PRODUCTION',
    categoryLabel: 'Production',
    subcategory: 'LED Screen & Video Processing',
    description: '140 m2 Outdoor P3.9 High Refresh LED (Center 16x6m + 2 Wings 8x4m) + Barco S3 Processor',
    vendorId: 'vnd-003',
    vendorName: 'PT Citra Visual Mandiri',
    quantity: 1,
    unit: 'set',
    estimatedUnitCost: 260000000,
    estimatedTotal: 260000000,
    actualUnitCost: 275000000,
    actualTotal: 275000000,
    variance: -15000000, // OVER BUDGET
    taxRate: 11,
    taxAmount: 30250000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PENDING',
    approvalStatus: 'PENDING',
    dueDate: '2027-05-12',
    notes: 'Penambahan tinggi wing LED 2 meter atas permintaan promotor untuk branding sponsor.',
    paidAmount: 130000000,
  },
  {
    id: 'bdg-011',
    eventId: 'evt-001',
    category: 'PRODUCTION',
    categoryLabel: 'Production',
    subcategory: 'Lighting & Special Effects',
    description: '70 Robe MegaPointe, 36 Martin MAC Aura, 16 ClayPaky Sharpy, 8 CO2 Jets, 4 Flame Throwers, GrandMA3',
    vendorId: 'vnd-007',
    vendorName: 'PT Cahaya Kilau Abadi',
    quantity: 1,
    unit: 'set',
    estimatedUnitCost: 210000000,
    estimatedTotal: 210000000,
    actualUnitCost: 210000000,
    actualTotal: 210000000,
    variance: 0,
    taxRate: 11,
    taxAmount: 23100000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-09',
    notes: 'Termasuk operator lighting show and timecode cue sync.',
    paidAmount: 210000000,
  },
  {
    id: 'bdg-012',
    eventId: 'evt-001',
    category: 'PRODUCTION',
    categoryLabel: 'Production',
    subcategory: 'Power & Generator',
    description: '3 unit Silent Genset 250 kVA Synchronized + 1 unit 150 kVA Vendor Booth + 5.000 L Solar Industri B35',
    vendorId: 'vnd-004',
    vendorName: 'PT Daya Solusi Nusantara',
    quantity: 1,
    unit: 'paket',
    estimatedUnitCost: 125000000,
    estimatedTotal: 125000000,
    actualUnitCost: 120000000,
    actualTotal: 120000000,
    variance: 5000000, // SAVING
    taxRate: 11,
    taxAmount: 13200000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PARTIALLY_PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-11',
    notes: 'Supply bahan bakar dan operator teknis standby 24 jam.',
    paidAmount: 60000000,
  },

  // Event 001: Operations & Security & Permit
  {
    id: 'bdg-013',
    eventId: 'evt-001',
    category: 'OPERATIONS',
    categoryLabel: 'Operations',
    subcategory: 'Security & Crowd Management',
    description: '150 Personil Pengamanan Garda Wibawa (Gate, Barricade, Backstage, Parking) + Koordinasi Brimob',
    vendorId: 'vnd-006',
    vendorName: 'PT Garda Wibawa Solusi',
    quantity: 1,
    unit: 'kontrak',
    estimatedUnitCost: 165000000,
    estimatedTotal: 165000000,
    actualUnitCost: 165000000,
    actualTotal: 165000000,
    variance: 0,
    taxRate: 2,
    taxAmount: 3300000,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'SCHEDULED',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-14',
    notes: 'Posko pengamanan gabungan di Pintu Barat.',
    paidAmount: 50000000,
  },
  {
    id: 'bdg-014',
    eventId: 'evt-001',
    category: 'OPERATIONS',
    categoryLabel: 'Operations',
    subcategory: 'Medical & Emergency Ambulance',
    description: '3 Unit Ambulance ICU Mobile Standby + 2 Dokter Spesialis Trauma + 8 Paramedis PMI DIY',
    vendorName: 'RSUP Dr. Sardjito & PMI DIY',
    quantity: 3,
    unit: 'hari',
    estimatedUnitCost: 15000000,
    estimatedTotal: 45000000,
    actualUnitCost: 45000000,
    actualTotal: 45000000,
    variance: 0,
    taxRate: 0,
    taxAmount: 0,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-13',
    notes: 'Rujukan rumah sakit terdekat RS Panti Rapih & RS Sardjito.',
    paidAmount: 45000000,
  },
  {
    id: 'bdg-015',
    eventId: 'evt-001',
    category: 'ADMINISTRATION',
    categoryLabel: 'Administration',
    subcategory: 'Legal, Police Permit & Satgas',
    description: 'Izin Keramaian Mabes Polri & Polda DIY, Rekomendasi Satgas, Hak Cipta WAMI/LMKN Musik',
    vendorName: 'Kantor Hukum & Asosiasi LMKN',
    quantity: 1,
    unit: 'paket',
    estimatedUnitCost: 85000000,
    estimatedTotal: 85000000,
    actualUnitCost: 85000000,
    actualTotal: 85000000,
    variance: 0,
    taxRate: 0,
    taxAmount: 0,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'PAID',
    approvalStatus: 'APPROVED',
    dueDate: '2027-04-20',
    notes: 'Surat Izin Keramaian No: S.IK/48/IV/YAN.2.1/2027/Baintelkam terbit.',
    paidAmount: 85000000,
  },
  {
    id: 'bdg-016',
    eventId: 'evt-001',
    category: 'CONTINGENCY',
    categoryLabel: 'Contingency',
    subcategory: 'Emergency Reserve Fund',
    description: 'Dana Cadangan Darurat (Hujan lebat, penambahan tenda darurat, genset cadangan)',
    vendorName: 'Internal Escrow Reserve',
    quantity: 1,
    unit: 'lot',
    estimatedUnitCost: 150000000,
    estimatedTotal: 150000000,
    actualUnitCost: 85000000,
    actualTotal: 85000000,
    variance: 65000000, // HEAVY SAVING!
    taxRate: 0,
    taxAmount: 0,
    discount: 0,
    currency: 'IDR',
    paymentStatus: 'SCHEDULED',
    approvalStatus: 'APPROVED',
    dueDate: '2027-05-17',
    notes: 'Sisa cadangan tidak terpakai dikembalikan ke kas panitia.',
    paidAmount: 0,
  },
];

export const SEED_ARTISTS: Artist[] = [
  {
    id: 'art-001',
    eventId: 'evt-001',
    name: 'Sheila On 7',
    type: 'Headliner',
    agency: '507 Management',
    management: 'Barkah',
    contactPerson: 'Adhy Permana (Road Manager)',
    phone: '+62 811-255-0507',
    email: 'booking@sheilaon7.com',
    genre: 'Pop Rock',
    country: 'Indonesia',
    city: 'Yogyakarta',
    performanceDuration: 90,
    setTime: '2027-05-15T21:00:00',
    arrivalTime: '2027-05-15T17:30:00',
    departureTime: '2027-05-15T23:30:00',
    fee: 450000000,
    tax: 11250000,
    transportAllowance: 25000000,
    accommodationDetail: 'Hotel Tentrem Yogyakarta: 1 Executive Suite (Duta), 3 Junior Suites, 4 Deluxe',
    bookingStatus: 'Contracted',
    paymentStatus: 'PARTIALLY_PAID',
    contractStatus: 'Signed',
    technicalRider: {
      stageRequirement: 'Panggung minimal 18m x 12m, drum riser hidrolik 3m x 2.5m x 0.6m karpet hitam.',
      audioRequirement: 'FOH Console Digico SD7 / Avid S6L 48 channel, PA System L-Acoustics K2 24 box.',
      monitorSystem: 'In-Ear Monitor Sennheiser G4 IEM (6 unit set) + D&B M4 Floor Wedge (4 pairs).',
      backlineList: [
        'Ampeg SVT-CL + 810E Bass Cab',
        'Fender Twin Reverb 65 Reissue',
        'Marshall JCM 900 Guitar Head + 1960A Cab',
        'Yamaha Absolute Hybrid Maple Drum Set (22, 10, 12, 16)',
        'Nord Stage 3 88-key Keyboard',
      ],
      microphoneSpec: [
        'Shure Axient Digital Wireless SM58 Capsule (Lead Vocal Duta)',
        'Shure Beta 58A (Backing Eross & Adam)',
        'Shure Beta 91A & Beta 52A (Kick Drum)',
        'Sennheiser e604 (Toms)',
      ],
      lightingMood: 'Warm tungsten, dynamic amber beam for ballad, high-energy white strobe chorus.',
      videoVisualSpec: 'Sync Timecode visual 3840x2160 prores backdrop, camera live-feed switch.',
      powerRequirement: 'Clean Audio Power isolated grounding max 1.5 ohm, 63A 3-Phase stage left & right.',
      stagePlotAttached: true,
      inputListAttached: true,
      notes: 'Soundcheck wajib dilakukan H-1 (14 Mei) pukul 16:00 - 18:00 WIB tanpa penonton di venue.',
    },
    hospitalityRider: {
      dressingRooms: '2 Ruang ganti AC dingin berkarpet bersih dengan sofa empuk, cermin rias full body, kamar mandi dalam.',
      foodAndBeverage: [
        'Air mineral Evian & Cleo suhu ruang 4 karton',
        'Kopi tubruk lokal Jogja biji fresh grind + kettle listrik',
        'Buah-buahan segar: pisang cavendish, apel fuji, anggur tanpa biji',
        'Jajanan pasar khas Yogyakarta: lemper, lumpia rebung, bakpia kukus',
        'Handuk bersih hitam kecil 12 pcs di panggung',
      ],
      hotelRequirement: 'Tentrem Hotel Yogyakarta bintang 5, check-in 14 Mei, check-out 16 Mei.',
      transportation: '1 Toyota Alphard New Modellista untuk Duta & keluarga, 2 Toyota HiAce Premio untuk personel & kru.',
      securityDetail: '4 Bodyguard berseragam hitam mendampingi dari hotel hingga backstage dan panggung.',
      guestListQuota: 25,
      specialRequests: [
        'Dilarang merokok di area ruang ganti utama artis',
        'Akses backstage steril dari selfie penonton/panitia umum',
      ],
    },
    contract: {
      id: 'ctr-001',
      artistId: 'art-001',
      eventId: 'evt-001',
      contractNumber: 'CTR-SO7-UGM-2027-01',
      contractDate: '2027-02-15',
      contractStart: '2027-05-14',
      contractEnd: '2027-05-16',
      fee: 450000000,
      tax: 11250000,
      totalContractValue: 461250000,
      deposit: 225000000,
      remainingPayment: 225000000,
      paymentTerms: '50% saat kontrak ditandatangani, 50% H-5 sebelum pementasan.',
      cancellationTerms: 'Force majeure akibat bencana alam atau larangan aparat keamanan: reschedule jadwal.',
      status: 'Active',
      contractDocumentName: 'Perjanjian_Kerja_Sama_SO7_DiesNatalis2027_Signed.pdf',
      milestones: [
        {
          name: 'Deposit (50%)',
          percentage: 50,
          amount: 225000000,
          dueDate: '2027-02-28',
          status: 'PAID',
          paidDate: '2027-02-27',
        },
        {
          name: 'Final Payment (50%)',
          percentage: 50,
          amount: 225000000,
          dueDate: '2027-05-10',
          status: 'PENDING',
        },
      ],
      notes: 'Klausul eksklusivitas: tidak tampil di DIY & Jateng 30 hari sebelum event.',
    },
    notes: 'Kondisi pita suara Duta prima. Rider teknis disepakati 100% oleh Chief Sound SAV Mandiri.',
  },
  {
    id: 'art-002',
    eventId: 'evt-001',
    name: 'Hindia (Baskara Putra)',
    type: 'Supporting Artist',
    agency: 'Sun Eater',
    management: 'Kiki Ucup',
    contactPerson: 'Kukuh Rizal',
    phone: '+62 812-9988-7766',
    email: 'booking@suneater.id',
    genre: 'Indie Rock / Alternative',
    country: 'Indonesia',
    city: 'Jakarta',
    performanceDuration: 60,
    setTime: '2027-05-15T19:40:00',
    arrivalTime: '2027-05-15T17:00:00',
    departureTime: '2027-05-15T22:00:00',
    fee: 125000000,
    tax: 3125000,
    transportAllowance: 15000000,
    accommodationDetail: 'Hotel Grand Mercure Yogyakarta (5 Superior Rooms)',
    bookingStatus: 'Contracted',
    paymentStatus: 'PAID',
    contractStatus: 'Signed',
    technicalRider: {
      stageRequirement: 'Panggung minimal 14m x 10m dengan lighting dramatis.',
      audioRequirement: 'Midas M32 / Yamaha CL5, Shure Wireless KSM9.',
      monitorSystem: 'In Ear Monitor 5 lines.',
      backlineList: ['Kemper Profiler Stage x 2', 'Aguilar Tone Hammer Bass', 'Yamaha Tour Custom Drum'],
      microphoneSpec: ['Shure KSM9 Wireless', 'Sennheiser e906 for guitars'],
      lightingMood: 'Deep blue, crimson red, silhouette backlighting.',
      videoVisualSpec: 'Visual lyrics sync 1080p 60fps.',
      powerRequirement: '40A single phase.',
      stagePlotAttached: true,
      inputListAttached: true,
      notes: 'Soundcheck 15 Mei pukul 13:00 - 14:00 WIB.',
    },
    hospitalityRider: {
      dressingRooms: '1 AC room with mirror and 6 comfortable chairs.',
      foodAndBeverage: ['Air mineral 2 karton', 'Kopi cold brew 10 botol', 'Pizza hangat 2 loyang'],
      hotelRequirement: 'Grand Mercure 4 bintang.',
      transportation: '1 Toyota HiAce Premio.',
      securityDetail: '2 Personil.',
      guestListQuota: 10,
      specialRequests: ['Tersedia asbak di luar ruang ganti'],
    },
    notes: 'Sudah lunas 100%. Tim visual telah mengirimkan aset video 4K.',
  },
  {
    id: 'art-003',
    eventId: 'evt-001',
    name: 'Reality Club',
    type: 'Band',
    agency: 'Dominion Records',
    management: 'Faris Luthfi',
    contactPerson: 'Faris Luthfi',
    phone: '+62 813-2211-0099',
    email: 'mgmt@realityclubmusic.com',
    genre: 'Indie Rock',
    country: 'Indonesia',
    city: 'Jakarta',
    performanceDuration: 50,
    setTime: '2027-05-15T18:30:00',
    arrivalTime: '2027-05-15T16:00:00',
    departureTime: '2027-05-15T21:00:00',
    fee: 85000000,
    tax: 2125000,
    transportAllowance: 12000000,
    accommodationDetail: 'Hotel Tentrem Deluxe Room (4 rooms)',
    bookingStatus: 'Confirmed',
    paymentStatus: 'PARTIALLY_PAID',
    contractStatus: 'Signed',
    technicalRider: {
      stageRequirement: 'Dual guitar + keyboard stage plot.',
      audioRequirement: 'Avid Venue SC48 or Yamaha CL5.',
      monitorSystem: '4 Wedge monitors + 2 IEM.',
      backlineList: ['Roland JC-120', 'Vox AC30', 'Ampeg SVT-3 Pro', 'Pearl Masters Drum'],
      microphoneSpec: ['Shure SM58 x 4', 'Sennheiser e845'],
      lightingMood: 'Vintage warm, indie pop energetic pastels.',
      videoVisualSpec: 'Cinema 2.35:1 vintage grain visual visuals.',
      powerRequirement: '30A clean ground.',
      stagePlotAttached: true,
      inputListAttached: true,
      notes: 'Soundcheck 15 Mei 14:00 - 15:00 WIB.',
    },
    hospitalityRider: {
      dressingRooms: '1 AC room with snacks and mirror.',
      foodAndBeverage: ['Air mineral', 'Fruit platter', 'Pocari sweat 12 botol'],
      hotelRequirement: 'Tentrem Hotel.',
      transportation: 'HiAce commuter.',
      securityDetail: '2 guards.',
      guestListQuota: 8,
      specialRequests: ['Teh hangat tanpa gula'],
    },
    notes: 'Pelunasan sisa 50% akan diproses H-7.',
  },
  {
    id: 'art-004',
    eventId: 'evt-001',
    name: 'Dipha Barus',
    type: 'DJ',
    agency: 'Pon Your Tone',
    management: 'Agatha',
    contactPerson: 'Reza Mahendra',
    phone: '+62 811-9988-1122',
    email: 'booking@diphabarus.com',
    genre: 'House / Electronic / Dance',
    country: 'Indonesia',
    city: 'Jakarta',
    performanceDuration: 60,
    setTime: '2027-05-15T22:30:00',
    arrivalTime: '2027-05-15T20:00:00',
    departureTime: '2027-05-16T01:00:00',
    fee: 75000000,
    tax: 1875000,
    transportAllowance: 10000000,
    accommodationDetail: 'Tentrem Suite Room (1 room)',
    bookingStatus: 'Confirmed',
    paymentStatus: 'SCHEDULED',
    contractStatus: 'Signed',
    technicalRider: {
      stageRequirement: 'DJ Booth kokoh tinggi 95cm tanpa goyang.',
      audioRequirement: 'Subwoofer punchy, sub-bass 35Hz respon solid.',
      monitorSystem: 'DJ Monitor L-Acoustics Kara II 2 stacks stereo.',
      backlineList: ['Pioneer DJ CDJ-3000 (3 units)', 'Pioneer DJM-V10 (1 unit) with latest firmware'],
      microphoneSpec: ['Shure UR4D Wireless Beta 58'],
      lightingMood: 'High speed laser array, CO2 blast, strobe bursts.',
      videoVisualSpec: 'Reactive visual mapping 60fps.',
      powerRequirement: 'Clean isolated UPS power.',
      stagePlotAttached: true,
      inputListAttached: true,
      notes: 'Pastikan firmware CDJ-3000 updated ke versi terbaru.',
    },
    hospitalityRider: {
      dressingRooms: '1 private AC room.',
      foodAndBeverage: ['Kelapa muda murni 2 butir', 'Red Bull 6 kaleng', 'Handuk dingin 4 pcs'],
      hotelRequirement: 'Tentrem Hotel.',
      transportation: 'Innova Zenix Hybrid.',
      securityDetail: '2 guards.',
      guestListQuota: 5,
      specialRequests: ['Earplugs high fidelity standby'],
    },
    notes: 'Penutup konser akbar UGM Festival.',
  },
];

export const SEED_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-001',
    poNumber: 'PO-2027-SAV-001',
    eventId: 'evt-001',
    vendorId: 'vnd-001',
    vendorName: 'PT Sumber Audio Visual Mandiri',
    date: '2027-03-10',
    expectedDelivery: '2027-05-11',
    paymentTerms: 'Term 1: 50% DP, Term 2: 50% Selesai Event',
    subtotal: 380000000,
    tax: 41800000,
    discount: 0,
    total: 421800000,
    paidAmount: 190000000,
    status: 'In Progress',
    approvalRequired: true,
    approvedBy: 'Dimas Arioseno',
    approvedAt: '2027-03-11T10:00:00Z',
    items: [
      {
        id: 'poi-001',
        description: 'L-Acoustics K2 Line Array System (24 Box) + Rigging Frame',
        quantity: 24,
        unit: 'box',
        unitPrice: 10000000,
        total: 240000000,
      },
      {
        id: 'poi-002',
        description: 'L-Acoustics KS28 Subwoofer (16 Box)',
        quantity: 16,
        unit: 'box',
        unitPrice: 5000000,
        total: 80000000,
      },
      {
        id: 'poi-003',
        description: 'Digico SD7 Dual Engine FOH & Monitor Surface Set',
        quantity: 2,
        unit: 'set',
        unitPrice: 30000000,
        total: 60000000,
      },
    ],
  },
  {
    id: 'po-002',
    poNumber: 'PO-2027-MEP-002',
    eventId: 'evt-001',
    vendorId: 'vnd-002',
    vendorName: 'Mata Elang Production',
    date: '2027-03-15',
    expectedDelivery: '2027-05-11',
    paymentTerms: 'Term 1: 50% DP, Term 2: 50% Load Out',
    subtotal: 320000000,
    tax: 35200000,
    discount: 0,
    total: 355200000,
    paidAmount: 160000000,
    status: 'In Progress',
    approvalRequired: true,
    approvedBy: 'Hendra Setiawan',
    approvedAt: '2027-03-16T11:00:00Z',
    items: [
      {
        id: 'poi-004',
        description: 'Layher Heavy Duty Stage 24m x 16m + Roofing 14m High',
        quantity: 1,
        unit: 'set',
        unitPrice: 220000000,
        total: 220000000,
      },
      {
        id: 'poi-005',
        description: 'FOH Double Decker Control Tower & Mojo Barricade 120m',
        quantity: 1,
        unit: 'set',
        unitPrice: 100000000,
        total: 100000000,
      },
    ],
  },
  {
    id: 'po-003',
    poNumber: 'PO-2027-CVM-003',
    eventId: 'evt-001',
    vendorId: 'vnd-003',
    vendorName: 'PT Citra Visual Mandiri',
    date: '2027-03-20',
    expectedDelivery: '2027-05-12',
    paymentTerms: '50% DP, 50% Pelunasan H-2',
    subtotal: 275000000,
    tax: 30250000,
    discount: 0,
    total: 305250000,
    paidAmount: 130000000,
    status: 'Approved',
    approvalRequired: true,
    approvedBy: 'Dimas Arioseno',
    approvedAt: '2027-03-22T09:00:00Z',
    items: [
      {
        id: 'poi-006',
        description: 'Outdoor LED P3.9 High Refresh (140 m2) + Barco S3 Processor',
        quantity: 140,
        unit: 'm2',
        unitPrice: 1964285,
        total: 275000000,
      },
    ],
  },
];

export const SEED_REVENUES: RevenueItem[] = [
  {
    id: 'rev-001',
    eventId: 'evt-001',
    category: 'Client Project Fee',
    description: 'Dana Alokasi Anggaran Kemahasiswaan DKA UGM',
    estimatedRevenue: 500000000,
    actualRevenue: 500000000,
    received: 500000000,
    outstanding: 0,
    dueDate: '2027-02-15',
    paymentStatus: 'PAID',
    payerName: 'Universitas Gadjah Mada',
    notes: 'Hibah kegiatan ormawa dies natalis.',
  },
  {
    id: 'rev-002',
    eventId: 'evt-001',
    category: 'Sponsorship',
    description: 'Telkomsel - Platinum Title Sponsor Festival UGM 2027',
    estimatedRevenue: 1200000000,
    actualRevenue: 1200000000,
    received: 1000000000,
    outstanding: 200000000,
    dueDate: '2027-05-20',
    paymentStatus: 'PARTIALLY_PAID',
    payerName: 'PT Telekomunikasi Selular',
    notes: 'Termin 1 (Rp 1M) diterima. Termin 2 (Rp 200jt) setelah LPJ sponsor selesai.',
  },
  {
    id: 'rev-003',
    eventId: 'evt-001',
    category: 'Sponsorship',
    description: 'Bank Mandiri (Livin by Mandiri) - Gold Official Banking Partner',
    estimatedRevenue: 650000000,
    actualRevenue: 650000000,
    received: 650000000,
    outstanding: 0,
    dueDate: '2027-04-10',
    paymentStatus: 'PAID',
    payerName: 'PT Bank Mandiri (Persero) Tbk',
    notes: 'Kerjasama ticketing cashless via Livin Sukha Mandiri.',
  },
  {
    id: 'rev-004',
    eventId: 'evt-001',
    category: 'Ticket Sales',
    description: 'Penjualan Tiket Early Bird, Presale 1 & 2, General Admission (20.000 Tiket)',
    estimatedRevenue: 1250000000,
    actualRevenue: 1320000000,
    received: 1120000000,
    outstanding: 200000000,
    dueDate: '2027-05-18',
    paymentStatus: 'PARTIALLY_PAID',
    payerName: 'Platform Ticketing Yesplis / Tiket.com',
    notes: 'Target tiket tercapai 105%. Settlement bertahap dari mitra aggregator.',
  },
  {
    id: 'rev-005',
    eventId: 'evt-001',
    category: 'Booth Rental',
    description: 'Sewa 28 Booth Kuliner & Merchandise UMKM Mahasiswa & Brand',
    estimatedRevenue: 150000000,
    actualRevenue: 150000000,
    received: 100000000,
    outstanding: 50000000,
    dueDate: '2027-05-12',
    paymentStatus: 'PARTIALLY_PAID',
    payerName: 'Tenant Paguyuban Kuliner Jogja',
    notes: 'Pelunasan H-3 sebelum loading booth.',
  },
];

export const SEED_CREW: CrewAssignment[] = [
  {
    id: 'crw-001',
    eventId: 'evt-001',
    name: 'Citra Kirana Dewi',
    role: 'Event Director',
    contact: '+62 811-2233-1111',
    callTime: '07:00 WIB',
    workTime: '07:00 - 24:00 WIB',
    rate: 15000000,
    overtime: 0,
    paymentStatus: 'PAID',
    notes: 'Pemimpin operasional menyeluruh festival.',
  },
  {
    id: 'crw-002',
    eventId: 'evt-001',
    name: 'Dimas Arioseno',
    role: 'Project Manager',
    contact: '+62 812-3344-2222',
    callTime: '07:00 WIB',
    workTime: '07:00 - 24:00 WIB',
    rate: 12500000,
    overtime: 0,
    paymentStatus: 'PAID',
    notes: 'Koordinasi perizinan, vendor, dan timeline kerja.',
  },
  {
    id: 'crw-003',
    eventId: 'evt-001',
    name: 'Hendra Setiawan',
    role: 'Technical Director',
    contact: '+62 813-4455-3333',
    callTime: '06:30 WIB',
    workTime: '06:30 - 01:00 WIB',
    rate: 10000000,
    overtime: 1500000,
    paymentStatus: 'SCHEDULED',
    notes: 'Bertanggung jawab atas kelistrikan, genset, dan safety rigging.',
  },
  {
    id: 'crw-004',
    eventId: 'evt-001',
    name: 'Sari Wulandari',
    role: 'Stage Manager',
    contact: '+62 812-5566-4444',
    callTime: '10:00 WIB',
    workTime: '10:00 - 24:00 WIB',
    rate: 7500000,
    overtime: 0,
    paymentStatus: 'SCHEDULED',
    notes: 'Pengaturan stage crew, mic changeover, dan pergantian instrumen.',
  },
  {
    id: 'crw-005',
    eventId: 'evt-001',
    name: 'Bagus Pratama',
    role: 'Show Caller',
    contact: '+62 811-6677-5555',
    callTime: '12:00 WIB',
    workTime: '12:00 - 24:00 WIB',
    rate: 8000000,
    overtime: 0,
    paymentStatus: 'SCHEDULED',
    notes: 'Pemandu waktu rundown, visual cue, audio trigger, dan kembang api.',
  },
  {
    id: 'crw-006',
    eventId: 'evt-001',
    name: 'Anisa Rahma',
    role: 'Hospitality',
    contact: '+62 813-7788-6666',
    callTime: '08:00 WIB',
    workTime: '08:00 - 24:00 WIB',
    rate: 4500000,
    overtime: 0,
    paymentStatus: 'SCHEDULED',
    notes: 'Lead Liaison Officer artis (Sheila On 7 & Hindia).',
  },
];

export const SEED_TASKS: Task[] = [
  {
    id: 'tsk-001',
    eventId: 'evt-001',
    name: 'Finalisasi Perjanjian Kontrak Sheila On 7',
    description: 'Penandatanganan addendum jam show dan konfirmasi kamar hotel.',
    category: 'Artist',
    assignee: 'Bima Satria Wardhana',
    priority: 'CRITICAL',
    startDate: '2027-02-10',
    dueDate: '2027-02-20',
    status: 'Completed',
    notes: 'Selesai dan telah ditandatangani kedua belah pihak.',
  },
  {
    id: 'tsk-002',
    eventId: 'evt-001',
    name: 'Penerbitan Surat Izin Keramaian Polda DIY',
    description: 'Penyerahan analisis dampak lalu lintas dan pengamanan crowd control.',
    category: 'Legal & Permit',
    assignee: 'Dimas Arioseno',
    priority: 'CRITICAL',
    startDate: '2027-03-01',
    dueDate: '2027-04-20',
    status: 'Completed',
    notes: 'SKCK & Surat Rekomendasi Kapolres Yogyakarta lengkap.',
  },
  {
    id: 'tsk-003',
    eventId: 'evt-001',
    name: 'Technical Meeting Produksi Bersama SAV Mandiri & Mata Elang',
    description: 'Pencocokan titik gantung rigging motor hoist dan delay tower speaker.',
    category: 'Production',
    assignee: 'Hendra Setiawan',
    priority: 'HIGH',
    startDate: '2027-04-25',
    dueDate: '2027-05-02',
    status: 'Completed',
    notes: 'Cad drawing & acoustic simulation Ease Focus disetujui.',
  },
  {
    id: 'tsk-004',
    eventId: 'evt-001',
    name: 'Pengujian Beban Genset & Synchronization Test',
    description: 'Uji sinkron 3x 250 kVA genset dengan beban load bank 80% selama 4 jam.',
    category: 'Technical',
    assignee: 'Hendra Setiawan',
    priority: 'HIGH',
    startDate: '2027-05-11',
    dueDate: '2027-05-12',
    status: 'In Progress',
    notes: 'Jadwal tes H-2 sore hari.',
  },
  {
    id: 'tsk-005',
    eventId: 'evt-001',
    name: 'Briefing Gabungan 150 Personil Pengamanan & Medis',
    description: 'Simulasi alur evakuasi penonton, penanganan medis darurat, dan sterilisasi panggung.',
    category: 'Security',
    assignee: 'Kapten Suryanto',
    priority: 'CRITICAL',
    startDate: '2027-05-13',
    dueDate: '2027-05-14',
    status: 'To Do',
    notes: 'Lokasi di Tribun Barat Stadion Mandala Krida pukul 09:00 WIB.',
  },
  {
    id: 'tsk-006',
    eventId: 'evt-001',
    name: 'Pelunasan Termin Terakhir Vendor LED & Sound',
    description: 'Pencairan sisa termin pembayaran sebelum artis tampil.',
    category: 'Finance',
    assignee: 'Ratna Ayu Larasati',
    priority: 'HIGH',
    startDate: '2027-05-05',
    dueDate: '2027-05-11',
    status: 'To Do',
    notes: 'Menunggu approval Direktur Keuangan.',
  },
];

export const SEED_RUNDOWN: RundownItem[] = [
  {
    id: 'rnd-001',
    eventId: 'evt-001',
    dayNumber: 1,
    date: '2027-05-14',
    time: '14:00 - 15:00',
    duration: 60,
    segment: 'Day 1: Open Gate & Crowd Ingress',
    description: 'Pemeriksaan metal detector, penukaran wristband, dan pembukaan area food festival.',
    talent: 'Background Music & DJ Ambient',
    venueArea: 'Gate 1, 2, 3 & Festival Plaza',
    pic: 'Head of Security & Ticketing',
    technicalCue: 'Low level PA background music',
    audioCue: 'Playlist Indie Lokal via FOH AUX',
    lightingCue: 'Daylight ambient stadium lights',
    videoCue: 'Sponsor Loop Telkomsel & Bank Mandiri on LED Wings',
    specialEffect: 'None',
    notes: 'Pastikan jalur ambulans di Gate 4 steril.',
    order: 1,
  },
  {
    id: 'rnd-002',
    eventId: 'evt-001',
    dayNumber: 1,
    date: '2027-05-14',
    time: '15:30 - 16:30',
    duration: 60,
    segment: 'Day 1: Gadjah Mada Youth Ensemble',
    description: 'Pentas kolosal orkestra & tari tradisional mahasiswa UGM.',
    talent: 'GMCO & Tari Rampoe UGM',
    venueArea: 'Main Stage',
    pic: 'Sari Wulandari (SM)',
    technicalCue: 'Full stage lighting warm wash',
    audioCue: 'Wireless headset mic 12 channels',
    lightingCue: 'Scene 01 Nusantara Golden Hue',
    videoCue: 'Video motion grafis Candi & Budaya',
    specialEffect: 'Low fog dry ice intro',
    notes: 'Mic hand-off ke MC tepat pukul 16:30.',
    order: 2,
  },
  {
    id: 'rnd-003',
    eventId: 'evt-001',
    dayNumber: 1,
    date: '2027-05-14',
    time: '16:30 - 17:00',
    duration: 30,
    segment: 'Day 1: Official Opening Ceremony',
    description: 'Sambutan pembuka oleh Rektor UGM dan Ketua Panitia.',
    talent: 'MC Yudha & Cindy ft. Rektor UGM',
    venueArea: 'Main Stage Center',
    pic: 'Dimas Arioseno',
    technicalCue: 'Podium mic active + spotlight',
    audioCue: 'Bumper audio intro gong',
    lightingCue: 'White spotlight 5600K on center stage',
    videoCue: 'UGM 77th Anniversary Crest & Live Camera',
    specialEffect: 'Confetti cannon shot on official opening',
    notes: 'Ketepatan waktu ketat 30 menit.',
    order: 3,
  },
  {
    id: 'rnd-004',
    eventId: 'evt-001',
    dayNumber: 2,
    date: '2027-05-15',
    time: '17:00 - 18:15',
    duration: 75,
    segment: 'Day 2: Sunset Break & Tenant Showcase',
    description: 'Jeda ibadah Maghrib, pemutaran video promosi sponsor dan talkshow UMKM santai.',
    talent: 'MC & Tenant Interview',
    venueArea: 'Festival Plaza & Stage Left',
    pic: 'Show Caller',
    technicalCue: 'Stage audio mute during Adzan',
    audioCue: 'Adzan Audio feed off, silence',
    lightingCue: 'Gentle indigo mood wash',
    videoCue: 'Waktu Solat Maghrib screen text',
    specialEffect: 'None',
    notes: 'Tepat hening suara musik selama azan berkumandang.',
    order: 4,
  },
  {
    id: 'rnd-005',
    eventId: 'evt-001',
    dayNumber: 2,
    date: '2027-05-15',
    time: '18:30 - 19:20',
    duration: 50,
    segment: 'Day 2: Performance: Reality Club',
    description: 'Penampilan band indie pop Reality Club dengan lagu hits Anything You Want.',
    talent: 'Reality Club',
    venueArea: 'Main Stage',
    pic: 'Sari Wulandari (SM)',
    technicalCue: 'Trigger Timecode 01:00:00',
    audioCue: 'Band Patch List Reality Club (Ch 1-28)',
    lightingCue: 'Scene 03 Neon Indie Drive GrandMA3',
    videoCue: 'Synchronized visual loop pack',
    specialEffect: 'CO2 jet at chorus intro',
    notes: 'Pergantian backline 20 menit menuju Hindia.',
    order: 5,
  },
  {
    id: 'rnd-006',
    eventId: 'evt-001',
    dayNumber: 2,
    date: '2027-05-15',
    time: '19:40 - 20:40',
    duration: 60,
    segment: 'Day 2: Performance: Hindia',
    description: 'Penampilan solo rock alternatif Baskara Putra dengan aransemen live band penuh.',
    talent: 'Hindia',
    venueArea: 'Main Stage',
    pic: 'Sari Wulandari (SM)',
    technicalCue: 'Trigger Timecode 02:00:00',
    audioCue: 'Patch List Hindia (Ch 1-32) In-Ear active',
    lightingCue: 'Scene 04 Deep Crimson & Heavy Strobes',
    videoCue: 'Monochrome typographic visual lyrics',
    specialEffect: 'Heavy cold spark jets on final song Evaluasi',
    notes: 'Kru Sheila On 7 stand by loading backstage tepat pukul 20:20.',
    order: 6,
  },
  {
    id: 'rnd-007',
    eventId: 'evt-001',
    dayNumber: 2,
    date: '2027-05-15',
    time: '21:00 - 22:30',
    duration: 90,
    segment: 'Day 2 Headliner: Sheila On 7 Mega Concert',
    description: 'Penampilan utama Sheila On 7 membawakan 16 lagu hits legendaris.',
    talent: 'Sheila On 7 (Duta, Eross, Adam & Band)',
    venueArea: 'Main Stage',
    pic: 'Bagus Pratama (Show Caller) & Adhy Permana',
    technicalCue: 'Trigger Main Timecode 03:00:00',
    audioCue: 'Master SO7 FOH Digico SD7 Show File loaded',
    lightingCue: 'GrandMA3 Timecode SO7 16 Tracks Playlist',
    videoCue: '4K Multi-cam Live Cut + SO7 Original Visuals',
    specialEffect: 'Pyro stage fireworks + 8 CO2 Jets + Streamer Cannon',
    notes: 'Momen puncak festival, pastikan barikade depan FOH aman terkendali.',
    order: 7,
  },
  {
    id: 'rnd-008',
    eventId: 'evt-001',
    dayNumber: 2,
    date: '2027-05-15',
    time: '22:30 - 23:30',
    duration: 60,
    segment: 'Day 2 After Party: Dipha Barus Electronic Finale',
    description: 'Pesta dansa elektronik penutup festival berpadu pesta kembang api spektakuler.',
    talent: 'Dipha Barus ft. Guest Vocalist',
    venueArea: 'Main Stage & Sky Fireworks Area',
    pic: 'Show Caller',
    technicalCue: 'Audio Master Limiter check 102dB',
    audioCue: 'Pioneer DJM-V10 Direct Link to PA',
    lightingCue: 'Laser Show + Strobe Chase High BPM',
    videoCue: 'High-speed audio-reactive 3D Visual Tunnel',
    specialEffect: 'Grand Finale Pyro & Sky Fireworks 200 shots',
    notes: 'Curfew ketat pukul 23:30 WIB tepat musik off sesuai izin kepolisian.',
    order: 8,
  },
  {
    id: 'rnd-009',
    eventId: 'evt-001',
    dayNumber: 3,
    date: '2027-05-16',
    time: '15:00 - 18:00',
    duration: 180,
    segment: 'Day 3: Cultural Carnival & UMKM Creative Awards',
    description: 'Karnaval budaya nusantara, pameran inovasi mahasiswa, dan pengumuman pemenang UMKM.',
    talent: 'Parade Budaya & Komunitas Kreatif',
    venueArea: 'Festival Plaza & Amphitheater',
    pic: 'Citra Kirana Dewi',
    technicalCue: 'Wireless roving mic + ambient coverage',
    audioCue: 'Acoustic & World Music Mix',
    lightingCue: 'Natural Daylight & Sunset Glow',
    videoCue: 'Highlight Reel Day 1 & Day 2',
    specialEffect: 'Daylight Smoke Streamers',
    notes: 'Persiapan bongkaran stage dimulai di area sayap luar.',
    order: 9,
  },
  {
    id: 'rnd-010',
    eventId: 'evt-001',
    dayNumber: 3,
    date: '2027-05-16',
    time: '19:30 - 21:00',
    duration: 90,
    segment: 'Day 3: Closing Ceremony & Official Strike Handover',
    description: 'Penutupan resmi seluruh rangkaian Dies Natalis dan penyerahan simbolis ke pihak rektorat.',
    talent: 'Panitia Inti & Rektorat',
    venueArea: 'Main Stage',
    pic: 'Dimas Arioseno',
    technicalCue: 'Standby load out crew at 21:00',
    audioCue: 'Hymne Gadjah Mada & Bagimu Negeri',
    lightingCue: 'Ceremonial Blue & White Uplighting',
    videoCue: 'Credit Title & Sponsor Roll',
    specialEffect: 'Cold Sparks Fountain 40 seconds',
    notes: 'Tepat pukul 21:30 mulai load out perlengkapan panggung.',
    order: 10,
  },
];

export const SEED_RISKS: RiskItem[] = [
  {
    id: 'rsk-001',
    eventId: 'evt-001',
    description: 'Hujan badai lebat dan angin kencang (>45 km/h) selama pertunjukan outdoor',
    category: 'Weather',
    probability: 3,
    impact: 5,
    severity: 15, // High Risk
    owner: 'Hendra Setiawan (Tech Director)',
    mitigation: 'Roofing stage bersertifikasi tahan angin 60 km/h, terpal waterproof penutup instrumen siap di sayap panggung.',
    contingency: 'Protokol emergency pause bila angin >50 km/h, amankan kabel listrik bertegangan tinggi.',
    status: 'Mitigated',
  },
  {
    id: 'rsk-002',
    eventId: 'evt-001',
    description: 'Kepadatan desakan penonton (crowd surge) di Gate A dan Barikade FOH',
    category: 'Crowd',
    probability: 4,
    impact: 4,
    severity: 16, // Critical Risk
    owner: 'Kapten Suryanto (Security Chief)',
    mitigation: 'Sistem zig-zag queuing barricade, pembagian 3 gelombang masuk, dan penyediaan 12 jalur pintu darurat lateral.',
    contingency: 'Water misting cooling fan, tim medis evakuasi di koridor khusus belakang barikade.',
    status: 'Mitigated',
  },
  {
    id: 'rsk-003',
    eventId: 'evt-001',
    description: 'Mogoknya genset utama FOH saat show berlangsung (Blackout)',
    category: 'Technical',
    probability: 2,
    impact: 5,
    severity: 10,
    owner: 'PT Daya Solusi Nusantara (PowerMax)',
    mitigation: 'Sistem 3 unit genset 250 kVA Synchronized paralel dengan Automatic Transfer Switch (ATS) 0.5 detik.',
    contingency: 'UPS online 60 kVA menyuplai FOH console dan sound processing agar tidak reboot bila terjadi switch.',
    status: 'Mitigated',
  },
  {
    id: 'rsk-004',
    eventId: 'evt-001',
    description: 'Penonton tanpa tiket menjebol pagar perimeter Stadion Mandala Krida',
    category: 'Security',
    probability: 3,
    impact: 4,
    severity: 12,
    owner: 'Garda Wibawa & Polsek Umbulharjo',
    mitigation: 'Ring 3 pengamanan perimeter luar berpagar kawat barier lapis baja & patroli motor polisi.',
    contingency: 'Penebalan personil Brimob di titik rawan sisi timur stadion.',
    status: 'Open',
  },
  {
    id: 'rsk-005',
    eventId: 'evt-001',
    description: 'Pelampauan budget akibat penambahan riders mendadak artis & kru',
    category: 'Financial',
    probability: 3,
    impact: 3,
    severity: 9,
    owner: 'Ratna Ayu Larasati (Finance)',
    mitigation: 'Alokasi dana cadangan (contingency reserve) sebesar Rp 150.000.000 dan approval ketat Project Manager.',
    contingency: 'Setiap pengeluaran >Rp 10.000.000 wajib disetujui Event Director.',
    status: 'Mitigated',
  },
];

export const SEED_APPROVALS: ApprovalRequest[] = [
  {
    id: 'app-001',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    type: 'BUDGET_OVERRUN',
    requester: 'Hendra Setiawan (Technical Director)',
    approver: 'Ratna Ayu Larasati (Finance Manager)',
    date: '2027-04-28T14:00:00Z',
    amount: 15000000,
    reason: 'Penambahan tinggi wing LED 2 meter untuk akomodasi sponsor title Telkomsel.',
    status: 'PENDING',
    comment: 'Menunggu konfirmasi apakah Telkomsel menanggung biaya selisih placement ini.',
    entityId: 'bdg-010',
  },
  {
    id: 'app-002',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    type: 'PURCHASE_ORDER',
    requester: 'Dimas Arioseno (Project Manager)',
    approver: 'Citra Kirana Dewi (Event Director)',
    date: '2027-03-15T11:00:00Z',
    amount: 355200000,
    reason: 'Penerbitan PO Rigging & Panggung Utama Layher Mata Elang Production.',
    status: 'APPROVED',
    comment: 'Disetujui, spesifikasi uji beban wind-load 60 km/h telah lengkap.',
    entityId: 'po-002',
  },
  {
    id: 'app-003',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    type: 'ARTIST_BOOKING',
    requester: 'Nadia Putri (Creative/Booking)',
    approver: 'Bima Satria Wardhana (Executive)',
    date: '2027-02-14T09:30:00Z',
    amount: 450000000,
    reason: 'Finalisasi booking fee Sheila On 7 sebagai headliner Dies Natalis UGM.',
    status: 'APPROVED',
    comment: 'Pilihan terbaik sesuai riset animo mahasiswa UGM, lanjutkan penandatanganan.',
    entityId: 'art-001',
  },
];

export const SEED_PAYMENTS: PaymentRecord[] = [
  {
    id: 'pay-001',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    payee: '507 Management (Sheila On 7)',
    type: 'ARTIST',
    reference: 'TRF-BCA-SO7-DP',
    amount: 225000000,
    dueDate: '2027-02-28',
    paymentDate: '2027-02-27',
    paymentMethod: 'Bank Transfer',
    status: 'PAID',
    notes: 'Pembayaran Uang Muka (DP 50%) Kontrak No. CTR-SO7-UGM-2027-01.',
  },
  {
    id: 'pay-002',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    payee: 'PT Sumber Audio Visual Mandiri',
    type: 'VENDOR',
    reference: 'TRF-MANDIRI-SAV-DP',
    amount: 190000000,
    dueDate: '2027-04-10',
    paymentDate: '2027-04-09',
    paymentMethod: 'Bank Transfer',
    status: 'PAID',
    notes: 'DP 50% Sound System L-Acoustics K2.',
  },
  {
    id: 'pay-003',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    payee: 'Mata Elang Production',
    type: 'VENDOR',
    reference: 'TRF-BCA-MEP-DP',
    amount: 160000000,
    dueDate: '2027-04-15',
    paymentDate: '2027-04-14',
    paymentMethod: 'Bank Transfer',
    status: 'PAID',
    notes: 'DP 50% Rigging Stage Layher.',
  },
  {
    id: 'pay-004',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    payee: '507 Management (Sheila On 7)',
    type: 'ARTIST',
    reference: 'INV-SO7-PELUNASAN',
    amount: 225000000,
    dueDate: '2027-05-10',
    paymentMethod: 'Bank Transfer',
    status: 'SCHEDULED',
    notes: 'Pelunasan sisa 50% honor artis Sheila On 7.',
  },
  {
    id: 'pay-005',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    payee: 'PT Garda Wibawa Solusi',
    type: 'VENDOR',
    reference: 'INV-SECURITY-SETTLE',
    amount: 115000000,
    dueDate: '2027-05-14',
    paymentMethod: 'Bank Transfer',
    status: 'SCHEDULED',
    notes: 'Pelunasan 150 personil pengamanan event.',
  },
];

export const SEED_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-001',
    eventId: 'evt-001',
    name: 'Surat_Izin_Keramaian_Mabes_Polri_PoldaDIY_2027.pdf',
    category: 'Permit',
    uploadedBy: 'Dimas Arioseno',
    uploadedAt: '2027-04-21T10:00:00Z',
    fileSize: '4.8 MB',
    fileType: 'application/pdf',
    status: 'Approved',
    notes: 'Izin keramaian sah kapasitas 25.000 orang dengan batasan waktu 23:30 WIB.',
  },
  {
    id: 'doc-002',
    eventId: 'evt-001',
    name: 'Perjanjian_Kerjasama_Sheila_On_7_Signed.pdf',
    category: 'Contract',
    uploadedBy: 'Bima Satria Wardhana',
    uploadedAt: '2027-02-16T14:30:00Z',
    fileSize: '3.2 MB',
    fileType: 'application/pdf',
    status: 'Approved',
    notes: 'Dokumen kontrak resmi bermaterai 10.000.',
  },
  {
    id: 'doc-003',
    eventId: 'evt-001',
    name: 'Technical_Rider_Audio_SAV_Mandiri_LAcoustics_K2.pdf',
    category: 'Technical Rider',
    uploadedBy: 'Hendra Setiawan',
    uploadedAt: '2027-03-12T09:15:00Z',
    fileSize: '8.4 MB',
    fileType: 'application/pdf',
    status: 'Final',
    notes: 'Spesifikasi detail PA system, rigging point, dan acoustic simulation EASE.',
  },
  {
    id: 'doc-004',
    eventId: 'evt-001',
    name: 'Production_Book_Master_Schedule_DiesNatalis_UGM_2027.pdf',
    category: 'Production Book',
    uploadedBy: 'Citra Kirana Dewi',
    uploadedAt: '2027-05-01T16:00:00Z',
    fileSize: '12.6 MB',
    fileType: 'application/pdf',
    status: 'Approved',
    notes: 'Buku panduan lengkap produksi untuk seluruh departemen & panitia.',
  },
];

export const SEED_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'aud-001',
    userId: 'usr-003',
    userName: 'Dimas Arioseno',
    userRole: 'PROJECT_MANAGER',
    timestamp: '2027-05-02T14:30:00Z',
    action: 'UPDATE',
    entity: 'BudgetItem',
    entityId: 'bdg-010',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    previousValue: 'actualTotal: Rp 260.000.000',
    newValue: 'actualTotal: Rp 275.000.000',
    notes: 'Penambahan ukuran screen LED wings kanan-kiri setinggi 2 meter.',
  },
  {
    id: 'aud-002',
    userId: 'usr-004',
    userName: 'Ratna Ayu Larasati',
    userRole: 'FINANCE',
    timestamp: '2027-04-14T09:20:00Z',
    action: 'CREATE',
    entity: 'PaymentRecord',
    entityId: 'pay-003',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    previousValue: 'Status: SCHEDULED',
    newValue: 'Status: PAID (Rp 160.000.000)',
    notes: 'Eksekusi pembayaran DP panggung Mata Elang Production.',
  },
  {
    id: 'aud-003',
    userId: 'usr-001',
    userName: 'Bima Satria Wardhana',
    userRole: 'SUPER_ADMIN',
    timestamp: '2027-02-15T16:00:00Z',
    action: 'APPROVE',
    entity: 'ArtistContract',
    entityId: 'ctr-001',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    previousValue: 'Status: Draft',
    newValue: 'Status: Signed & Active',
    notes: 'Persetujuan resmi kontrak Sheila On 7.',
  },
];

// FUTURE ERP LOGISTICS INTEGRATION REQUIREMENTS
// This abstraction specifies WHAT the event needs, allowing mcaesarar2-boop/erp-logistik
// to handle inventory availability, packages, warehouse stock, delivery, and return.
export const SEED_REQUIREMENTS: EventRequirement[] = [
  {
    id: 'req-001',
    eventId: 'evt-001',
    externalSystem: 'ERP_LOGISTICS',
    externalReference: 'RES-LOG-2027-8891',
    itemReference: 'L-Acoustics K2 Line Array Speaker',
    category: 'SOUND',
    description: 'Main PA Rigging System for Festival Outdoor 25k audience (Left 12, Right 12)',
    quantity: 24,
    unit: 'unit',
    requiredDate: '2027-05-11T08:00:00Z',
    returnDate: '2027-05-17T18:00:00Z',
    status: 'ALLOCATED',
    notes: 'Dialokasikan oleh ERP Logistik dari Gudang Utama Cakung.',
    reservedAt: '2027-03-15T10:00:00Z',
    deliveredAt: '2027-05-11T09:30:00Z',
    warehouseAssigned: 'Gudang Utama Cakung (Jakarta)',
  },
  {
    id: 'req-002',
    eventId: 'evt-001',
    externalSystem: 'ERP_LOGISTICS',
    externalReference: 'RES-LOG-2027-8892',
    itemReference: 'L-Acoustics KS28 High Power Subwoofer',
    category: 'SOUND',
    description: 'Cardioid Subwoofer Array Configuration',
    quantity: 16,
    unit: 'unit',
    requiredDate: '2027-05-11T08:00:00Z',
    returnDate: '2027-05-17T18:00:00Z',
    status: 'ALLOCATED',
    notes: 'Dialokasikan dari Gudang Cakung.',
    reservedAt: '2027-03-15T10:00:00Z',
    deliveredAt: '2027-05-11T09:30:00Z',
    warehouseAssigned: 'Gudang Utama Cakung (Jakarta)',
  },
  {
    id: 'req-003',
    eventId: 'evt-001',
    externalSystem: 'ERP_LOGISTICS',
    externalReference: 'RES-LOG-2027-8893',
    itemReference: 'Digico SD7 Digital Mixing Console (Optocore Dual Engine)',
    category: 'SOUND',
    description: 'FOH & Monitor Touring Surface with 56-in SD-Rack',
    quantity: 2,
    unit: 'flight-case',
    requiredDate: '2027-05-11T12:00:00Z',
    returnDate: '2027-05-17T12:00:00Z',
    status: 'RESERVED',
    notes: 'Flight case bersertifikat touring, siap kirim via armada logistik.',
    reservedAt: '2027-03-16T14:00:00Z',
    warehouseAssigned: 'Gudang Cabang Sleman (Yogyakarta)',
  },
  {
    id: 'req-004',
    eventId: 'evt-001',
    externalSystem: 'ERP_LOGISTICS',
    externalReference: 'RES-LOG-2027-8894',
    itemReference: 'Outdoor LED Screen P3.9 High Refresh (500x1000mm cabinet)',
    category: 'LED_VIDEO',
    description: 'Layar Utama & Sayap Panggung Outdoor Tahan Air IP65',
    quantity: 280,
    unit: 'panel',
    requiredDate: '2027-05-12T08:00:00Z',
    returnDate: '2027-05-17T15:00:00Z',
    status: 'REQUESTED',
    notes: 'Menunggu konfirmasi ketersediaan paket kabel & sending card dari ERP Logistik.',
    warehouseAssigned: 'Gudang Surabaya & Cakung',
  },
  {
    id: 'req-005',
    eventId: 'evt-001',
    externalSystem: 'ERP_LOGISTICS',
    itemReference: 'Silent Diesel Generator 250 kVA Cummins (Synchronized)',
    category: 'POWER_GENSET',
    description: 'Pembangkit Daya Panggung Utama',
    quantity: 3,
    unit: 'unit',
    requiredDate: '2027-05-11T08:00:00Z',
    returnDate: '2027-05-17T20:00:00Z',
    status: 'DRAFT',
    notes: 'Kebutuhan baru diidentifikasi oleh tim teknis.',
  },
  {
    id: 'req-006',
    eventId: 'evt-001',
    externalSystem: 'ERP_LOGISTICS',
    itemReference: 'Robe MegaPointe Moving Head Fixture',
    category: 'LIGHTING',
    description: 'Beam / Spot / Wash Hybrid Fixture',
    quantity: 48,
    unit: 'unit',
    requiredDate: '2027-05-12T08:00:00Z',
    returnDate: '2027-05-17T12:00:00Z',
    status: 'RESERVED',
    notes: 'Paket lighting panggung festival.',
    warehouseAssigned: 'Gudang Utama Cakung (Jakarta)',
  },
];

export const SEED_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Budget Overrun Warning',
    message: 'Pos LED Screen (CVM) mengalami over-budget Rp 15.000.000 pada event UGM Festival.',
    severity: 'WARNING',
    category: 'BUDGET',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    createdAt: '10m lalu',
    read: false,
    action: {
      type: 'NAVIGATE',
      eventId: 'evt-001',
      tab: 'BUDGET',
      label: 'Review Budget',
    },
  },
  {
    id: 'notif-2',
    title: 'Payment Due in 5 Days',
    message: 'Pelunasan Sheila On 7 sebesar Rp 225.000.000 jatuh tempo 10 Mei.',
    severity: 'CRITICAL',
    category: 'PAYMENT',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    createdAt: '1j lalu',
    read: false,
    action: {
      type: 'NAVIGATE',
      eventId: 'evt-001',
      tab: 'PAYMENTS',
      label: 'Check Payment',
    },
  },
  {
    id: 'notif-3',
    title: 'ERP Logistics Reserved',
    message: 'L-Acoustics K2 & Subwoofer telah di-reserve oleh ERP Logistik dari Gudang Cakung.',
    severity: 'INFO',
    category: 'LOGISTICS',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    createdAt: '3j lalu',
    read: false,
    action: {
      type: 'NAVIGATE',
      eventId: 'evt-001',
      tab: 'LOGISTICS_ERP',
      label: 'View Logistics',
    },
  },
  {
    id: 'notif-4',
    title: 'Critical Risk Alert',
    message: 'Risiko potensi cuaca ekstrem (hujan badai & angin kencang) di FOH Stadion Mandala Krida belum memiliki SOP mitigasi.',
    severity: 'CRITICAL',
    category: 'RISK',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    createdAt: '5j lalu',
    read: false,
    action: {
      type: 'NAVIGATE',
      eventId: 'evt-001',
      tab: 'RISKS',
      label: 'Mitigasi Risiko',
    },
  },
  {
    id: 'notif-5',
    title: 'PO Awaiting Approval',
    message: 'PO #PO-2027-001 Sewa Sound System & Rigging senilai Rp 180.000.000 siap diverifikasi Project Manager.',
    severity: 'WARNING',
    category: 'PROCUREMENT',
    eventId: 'evt-001',
    eventName: 'Gadjah Mada Youth Music & Arts Festival 2027',
    createdAt: '6j lalu',
    read: false,
    action: {
      type: 'NAVIGATE',
      eventId: 'evt-001',
      tab: 'PROCUREMENT',
      label: 'Review PO',
    },
  },
  {
    id: 'notif-6',
    title: 'System Security & Audit Update',
    message: 'Semua perubahan hak akses dan log aktivitas operasional berhasil disinkronkan ke pusat audit.',
    severity: 'SUCCESS',
    category: 'SYSTEM',
    createdAt: '1 hari lalu',
    read: true,
    action: {
      type: 'NAVIGATE',
      view: 'AUDIT_LOGS',
      label: 'Buka Audit Logs',
    },
  },
];

